version: '3.8'
services:
  gateway:
    build: gateway
    image: gateway
    container_name: ShareItGatewayContainer
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: server
    container_name: ShareItServerContainer
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5431/shareit

  db:
    image: postgres:13.7-alpine
    container_name: ShareItDBContainer
    ports:
      - "5431:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root